// Code generated by "stringer -type=GPO_LINK,GPOOptions -output=list_string_windows.go"; DO NOT EDIT.

package gp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GPLinkUnknown-0]
	_ = x[GPLinkMachine-1]
	_ = x[GPLinkSite-2]
	_ = x[GPLinkDomain-3]
	_ = x[GPLinkOrganizationalUnit-4]
}

const _GPO_LINK_name = "GPLinkUnknownGPLinkMachineGPLinkSiteGPLinkDomainGPLinkOrganizationalUnit"

var _GPO_LINK_index = [...]uint8{0, 13, 26, 36, 48, 72}

func (i GPO_LINK) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_GPO_LINK_index)-1 {
		return "GPO_LINK(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GPO_LINK_name[_GPO_LINK_index[idx]:_GPO_LINK_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GPO_FLAG_DISABLE-1]
	_ = x[GPO_FLAG_FORCE-2]
}

const _GPOOptions_name = "GPO_FLAG_DISABLEGPO_FLAG_FORCE"

var _GPOOptions_index = [...]uint8{0, 16, 30}

func (i GPOOptions) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_GPOOptions_index)-1 {
		return "GPOOptions(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GPOOptions_name[_GPOOptions_index[idx]:_GPOOptions_index[idx+1]]
}
